// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package dynamodb

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	SourceConfigAwsAccessKeyId     = "aws.accessKeyId"
	SourceConfigAwsRegion          = "aws.region"
	SourceConfigAwsSecretAccessKey = "aws.secretAccessKey"
	SourceConfigKey                = "key"
	SourceConfigTable              = "table"
)

func (SourceConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		SourceConfigAwsAccessKeyId: {
			Default:     "",
			Description: "",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		SourceConfigAwsRegion: {
			Default:     "",
			Description: "todo add sortKey?",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		SourceConfigAwsSecretAccessKey: {
			Default:     "",
			Description: "",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		SourceConfigKey: {
			Default:     "",
			Description: "",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		SourceConfigTable: {
			Default:     "",
			Description: "",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
	}
}
