// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package dynamodb

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	SourceConfigAwsAccessKeyId         = "aws.accessKeyId"
	SourceConfigAwsRegion              = "aws.region"
	SourceConfigAwsSecretAccessKey     = "aws.secretAccessKey"
	SourceConfigAwsUrl                 = "aws.url"
	SourceConfigDiscoveryPollingPeriod = "discoveryPollingPeriod"
	SourceConfigRecordsPollingPeriod   = "recordsPollingPeriod"
	SourceConfigSkipSnapshot           = "skipSnapshot"
	SourceConfigTable                  = "table"
)

func (SourceConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		SourceConfigAwsAccessKeyId: {
			Default:     "",
			Description: "AWS access key id.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		SourceConfigAwsRegion: {
			Default:     "",
			Description: "AWS region.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		SourceConfigAwsSecretAccessKey: {
			Default:     "",
			Description: "AWS secret access key.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		SourceConfigAwsUrl: {
			Default:     "",
			Description: "AWSURL The URL for AWS (useful when testing the connector with localstack).",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		SourceConfigDiscoveryPollingPeriod: {
			Default:     "10s",
			Description: "discovery polling period for the CDC mode of how often to check for new shards in the DynamoDB Stream, formatted as a time.Duration string.",
			Type:        config.ParameterTypeDuration,
			Validations: []config.Validation{},
		},
		SourceConfigRecordsPollingPeriod: {
			Default:     "5s",
			Description: "records polling period for the CDC mode of how often to get new records from a shard, formatted as a time.Duration string.",
			Type:        config.ParameterTypeDuration,
			Validations: []config.Validation{},
		},
		SourceConfigSkipSnapshot: {
			Default:     "false",
			Description: "skipSnapshot determines weather to skip the snapshot or not.",
			Type:        config.ParameterTypeBool,
			Validations: []config.Validation{},
		},
		SourceConfigTable: {
			Default:     "",
			Description: "Table is the DynamoDB table name to pull data from.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
	}
}
